apiVersion: v1
kind: Service
metadata:
  name: go-kube-service
spec:
  ports:
  - protocol: TCP
    # Port that is accessible outside
    port: 8080
    # Port that are exposed inside pods/containers
    targetPort: 3000
  selector:
    # Selector to Identify pods to loadbalance
    app: go-kube
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: go-kube-deployment
  name: go-kube-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-kube
    spec:
      containers:
      - name: main
        image: kenkoii/go-kube
        ports:
        - containerPort: 3000