apiVersion: v1
kind: ReplicationController
metadata:
  name: go-kube-rc
spec:
  replicas: 2
  selector:
    app: go-kube
  template:
    metadata:
      labels:
        app: go-kube
    spec:
      containers:
      - name: k8s-demo
        image: kenkoii/go-kube
        ports:
        - containerPort: 3000