apiVersion: v1
kind: Service
metadata:
  name: go-kube-service
spec:
  ports:
  - protocol: TCP
    # Port that is accessible outside
    port: 8080
    # Port that are exposed inside pods/containers
    targetPort: 3000
  selector:
    # Selector to Identify pods to loadbalance
    app: go-kube
  type: LoadBalancer
